name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v2

      - name: Composer Install
      - uses: php-actions/composer@v6

      - name: Composer Test 2
        run: |
          composer test
